

### This is where I test the backend without loading up the front end. Click Send Request to test different api stuff
GET /feed123 HTTP/1.1
Host: localhost:8000
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmOWQ2MjNkZGMyMTg2MTQzOGI5NjIiLCJlbWFpbCI6ImFiY0BhYmNAZ21haWwuY29tIiwiaWF0IjoxNjg1MDM2Mzg2LCJleHAiOjE2ODUxMjI3ODZ9.2H86_gNaip8aMmzZfn6PAacrnHEE9kGziV-q3L0MiaI



###
GET /home HTTP/1.1
Host: localhost:8000
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmOWQ2MjNkZGMyMTg2MTQzOGI5NjIiLCJlbWFpbCI6ImFiY0BhYmNAZ21haWwuY29tIiwiaWF0IjoxNjg1MDM2Mzg2LCJleHAiOjE2ODUxMjI3ODZ9.2H86_gNaip8aMmzZfn6PAacrnHEE9kGziV-q3L0MiaI

###

POST /feed123/new HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "content": "Just another test post(delete these test plz)"
}

###

POST /register HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "email": "abc@abc@gmail.com",
    "password": "abcd"
}

###

POST /login HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "email": "abc@abc@gmail.com",
    "password": "abcd"
}

###

GET / HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmOWQ2MjNkZGMyMTg2MTQzOGI5NjIiLCJlbWFpbCI6ImFiY0BhYmNAZ21haWwuY29tIiwiaWF0IjoxNjg1MDM2Mzg2LCJleHAiOjE2ODUxMjI3ODZ9.2H86_gNaip8aMmzZfn6PAacrnHEE9kGziV-q3L0MiaI

{
    "perPage": 11,
    "page": 2,
    "type": "forYou"
}

# token! eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmOWQ2MjNkZGMyMTg2MTQzOGI5NjIiLCJlbWFpbCI6ImFiY0BhYmNAZ21haWwuY29tIiwiaWF0IjoxNjg1MDM2Mzg2LCJleHAiOjE2ODUxMjI3ODZ9.2H86_gNaip8aMmzZfn6PAacrnHEE9kGziV-q3L0MiaI
###
POST / HTTP/1.1
Host: localhost:8000/upload
//Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1Mzk1OTM0LCJleHAiOjE2ODU0ODIzMzR9.I2wiBKCxhNxXk4okFtv0AdykWX8P5qHN0x2f1HuexAc

{

}


### /user/:username
GET /user/abc@abc.com HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

###
GET /post/6478cf38593c3e879d9edccd HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

###
GET /abc@abc.com HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

### /user/:username
GET /post/123 HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

### /user/:username getting post comments
GET /react/6478cf38593c3e879d9edccd HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

### /user/:username getting post comments 646fcc1fb83195e1c56cb2be
POST /follow/646fcc1fb83195e1c56cb2be HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2MxZmI4MzE5NWUxYzU2Y2IyYmUiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjg1NTk3Nzg2LCJleHAiOjE2ODU2ODQxODZ9.WvTi_wOzWD5aApO1sQZoTUs9tYiPvC0z4xcalj4sttg

{

}

### /user/:username getting post comments
###

GET /search123/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "q": "Fred"
}

###
GET /search/?q=zxy HTTP/1.1
Host: localhost:8000

### /user/:username getting post comments 646fcc1fb83195e1c56cb2be
PATCH  /me HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDZmY2M0ZmI4MzE5NWUxYzU2Y2IyYzMiLCJlbWFpbCI6InJpY2hhcmRAYWJjLmNvbSIsImlhdCI6MTY4NTc0ODczNCwiZXhwIjoxNjg1ODM1MTM0fQ.g3BFfi86usCbyZdmO8i-FdIN08_ia1agzZ6QWIYYLG0

{
    "username": "Richard22"
}